title: Let's cook
author: Mert Arel
email: mertarel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I like cooking. Is it possible to code about cooking?
  I don't know yet but I'll find out...

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  mertarel # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
